// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kujilabo/cocotola-translator-api/src/app/domain"
	mock "github.com/stretchr/testify/mock"

	service "github.com/kujilabo/cocotola-translator-api/src/app/service"

	testing "testing"
)

// CustomTranslationRepository is an autogenerated mock type for the CustomTranslationRepository type
type CustomTranslationRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, param
func (_m *CustomTranslationRepository) Add(ctx context.Context, param service.TranslationAddParameter) error {
	ret := _m.Called(ctx, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TranslationAddParameter) error); ok {
		r0 = rf(ctx, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Contain provides a mock function with given fields: ctx, lang2, text
func (_m *CustomTranslationRepository) Contain(ctx context.Context, lang2 domain.Lang2, text string) (bool, error) {
	ret := _m.Called(ctx, lang2, text)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string) bool); ok {
		r0 = rf(ctx, lang2, text)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string) error); ok {
		r1 = rf(ctx, lang2, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByFirstLetter provides a mock function with given fields: ctx, lang2, firstLetter
func (_m *CustomTranslationRepository) FindByFirstLetter(ctx context.Context, lang2 domain.Lang2, firstLetter string) ([]domain.Translation, error) {
	ret := _m.Called(ctx, lang2, firstLetter)

	var r0 []domain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string) []domain.Translation); ok {
		r0 = rf(ctx, lang2, firstLetter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string) error); ok {
		r1 = rf(ctx, lang2, firstLetter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByText provides a mock function with given fields: ctx, lang2, text
func (_m *CustomTranslationRepository) FindByText(ctx context.Context, lang2 domain.Lang2, text string) ([]domain.Translation, error) {
	ret := _m.Called(ctx, lang2, text)

	var r0 []domain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string) []domain.Translation); ok {
		r0 = rf(ctx, lang2, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string) error); ok {
		r1 = rf(ctx, lang2, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTextAndPos provides a mock function with given fields: ctx, lang2, text, pos
func (_m *CustomTranslationRepository) FindByTextAndPos(ctx context.Context, lang2 domain.Lang2, text string, pos domain.WordPos) (domain.Translation, error) {
	ret := _m.Called(ctx, lang2, text, pos)

	var r0 domain.Translation
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, domain.WordPos) domain.Translation); ok {
		r0 = rf(ctx, lang2, text, pos)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.Lang2, string, domain.WordPos) error); ok {
		r1 = rf(ctx, lang2, text, pos)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, lang2, text, pos
func (_m *CustomTranslationRepository) Remove(ctx context.Context, lang2 domain.Lang2, text string, pos domain.WordPos) error {
	ret := _m.Called(ctx, lang2, text, pos)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, domain.WordPos) error); ok {
		r0 = rf(ctx, lang2, text, pos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, lang2, text, pos, param
func (_m *CustomTranslationRepository) Update(ctx context.Context, lang2 domain.Lang2, text string, pos domain.WordPos, param service.TranslationUpdateParameter) error {
	ret := _m.Called(ctx, lang2, text, pos, param)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Lang2, string, domain.WordPos, service.TranslationUpdateParameter) error); ok {
		r0 = rf(ctx, lang2, text, pos, param)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCustomTranslationRepository creates a new instance of CustomTranslationRepository. It also registers a cleanup function to assert the mocks expectations.
func NewCustomTranslationRepository(t testing.TB) *CustomTranslationRepository {
	mock := &CustomTranslationRepository{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
