// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/kujilabo/cocotola-translator-api/src/app/service"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RepositoryFactory is an autogenerated mock type for the RepositoryFactory type
type RepositoryFactory struct {
	mock.Mock
}

// NewAzureTranslationRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewAzureTranslationRepository(ctx context.Context) service.AzureTranslationRepository {
	ret := _m.Called(ctx)

	var r0 service.AzureTranslationRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.AzureTranslationRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AzureTranslationRepository)
		}
	}

	return r0
}

// NewCustomTranslationRepository provides a mock function with given fields: ctx
func (_m *RepositoryFactory) NewCustomTranslationRepository(ctx context.Context) service.CustomTranslationRepository {
	ret := _m.Called(ctx)

	var r0 service.CustomTranslationRepository
	if rf, ok := ret.Get(0).(func(context.Context) service.CustomTranslationRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.CustomTranslationRepository)
		}
	}

	return r0
}

// NewRepositoryFactory creates a new instance of RepositoryFactory. It also registers a cleanup function to assert the mocks expectations.
func NewRepositoryFactory(t testing.TB) *RepositoryFactory {
	mock := &RepositoryFactory{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
