// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// TranslationUpdateParameter is an autogenerated mock type for the TranslationUpdateParameter type
type TranslationUpdateParameter struct {
	mock.Mock
}

// GetTranslated provides a mock function with given fields:
func (_m *TranslationUpdateParameter) GetTranslated() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewTranslationUpdateParameter creates a new instance of TranslationUpdateParameter. It also registers a cleanup function to assert the mocks expectations.
func NewTranslationUpdateParameter(t testing.TB) *TranslationUpdateParameter {
	mock := &TranslationUpdateParameter{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
