// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: proto/translator_user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DictionaryLookupParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromLang2 string `protobuf:"bytes,1,opt,name=fromLang2,proto3" json:"fromLang2,omitempty"`
	ToLang2   string `protobuf:"bytes,2,opt,name=toLang2,proto3" json:"toLang2,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DictionaryLookupParameter) Reset() {
	*x = DictionaryLookupParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryLookupParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryLookupParameter) ProtoMessage() {}

func (x *DictionaryLookupParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryLookupParameter.ProtoReflect.Descriptor instead.
func (*DictionaryLookupParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_user_proto_rawDescGZIP(), []int{0}
}

func (x *DictionaryLookupParameter) GetFromLang2() string {
	if x != nil {
		return x.FromLang2
	}
	return ""
}

func (x *DictionaryLookupParameter) GetToLang2() string {
	if x != nil {
		return x.ToLang2
	}
	return ""
}

func (x *DictionaryLookupParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DictionaryLookupWithPosParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromLang2 string `protobuf:"bytes,1,opt,name=fromLang2,proto3" json:"fromLang2,omitempty"`
	ToLang2   string `protobuf:"bytes,2,opt,name=toLang2,proto3" json:"toLang2,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Pos       int32  `protobuf:"varint,4,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *DictionaryLookupWithPosParameter) Reset() {
	*x = DictionaryLookupWithPosParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryLookupWithPosParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryLookupWithPosParameter) ProtoMessage() {}

func (x *DictionaryLookupWithPosParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryLookupWithPosParameter.ProtoReflect.Descriptor instead.
func (*DictionaryLookupWithPosParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_user_proto_rawDescGZIP(), []int{1}
}

func (x *DictionaryLookupWithPosParameter) GetFromLang2() string {
	if x != nil {
		return x.FromLang2
	}
	return ""
}

func (x *DictionaryLookupWithPosParameter) GetToLang2() string {
	if x != nil {
		return x.ToLang2
	}
	return ""
}

func (x *DictionaryLookupWithPosParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DictionaryLookupWithPosParameter) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type DictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2      string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos        int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Translated string `protobuf:"bytes,4,opt,name=translated,proto3" json:"translated,omitempty"`
	Provider   string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *DictionaryResponse) Reset() {
	*x = DictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryResponse) ProtoMessage() {}

func (x *DictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryResponse.ProtoReflect.Descriptor instead.
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_user_proto_rawDescGZIP(), []int{2}
}

func (x *DictionaryResponse) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *DictionaryResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DictionaryResponse) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *DictionaryResponse) GetTranslated() string {
	if x != nil {
		return x.Translated
	}
	return ""
}

func (x *DictionaryResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DictionaryLookupResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DictionaryResponse `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *DictionaryLookupResponses) Reset() {
	*x = DictionaryLookupResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryLookupResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryLookupResponses) ProtoMessage() {}

func (x *DictionaryLookupResponses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryLookupResponses.ProtoReflect.Descriptor instead.
func (*DictionaryLookupResponses) Descriptor() ([]byte, []int) {
	return file_proto_translator_user_proto_rawDescGZIP(), []int{3}
}

func (x *DictionaryLookupResponses) GetResults() []*DictionaryResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type DictionaryLookupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *DictionaryResponse `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *DictionaryLookupResponse) Reset() {
	*x = DictionaryLookupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryLookupResponse) ProtoMessage() {}

func (x *DictionaryLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryLookupResponse.ProtoReflect.Descriptor instead.
func (*DictionaryLookupResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_user_proto_rawDescGZIP(), []int{4}
}

func (x *DictionaryLookupResponse) GetResult() *DictionaryResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_translator_user_proto protoreflect.FileDescriptor

var file_proto_translator_user_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x19, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x6f, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x6f, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x80, 0x01,
	0x0a, 0x20, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x57, 0x69, 0x74, 0x68, 0x50, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x6e, 0x67, 0x32,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x6f, 0x4c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73,
	0x22, 0x8c, 0x01, 0x0a, 0x12, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22,
	0x50, 0x0a, 0x19, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x22, 0x4d, 0x0a, 0x18, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0xd1, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x58, 0x0a, 0x10, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x65, 0x0a,
	0x17, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x57, 0x69, 0x74, 0x68, 0x50, 0x6f, 0x73, 0x12, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x57, 0x69, 0x74, 0x68, 0x50, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x6b, 0x0a, 0x1f, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x75, 0x73, 0x65, 0x72, 0x42, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x6a, 0x69, 0x6c,
	0x61, 0x62, 0x6f, 0x2f, 0x63, 0x6f, 0x63, 0x6f, 0x74, 0x6f, 0x6c, 0x61, 0x2d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_translator_user_proto_rawDescOnce sync.Once
	file_proto_translator_user_proto_rawDescData = file_proto_translator_user_proto_rawDesc
)

func file_proto_translator_user_proto_rawDescGZIP() []byte {
	file_proto_translator_user_proto_rawDescOnce.Do(func() {
		file_proto_translator_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_translator_user_proto_rawDescData)
	})
	return file_proto_translator_user_proto_rawDescData
}

var file_proto_translator_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_translator_user_proto_goTypes = []interface{}{
	(*DictionaryLookupParameter)(nil),        // 0: proto.DictionaryLookupParameter
	(*DictionaryLookupWithPosParameter)(nil), // 1: proto.DictionaryLookupWithPosParameter
	(*DictionaryResponse)(nil),               // 2: proto.DictionaryResponse
	(*DictionaryLookupResponses)(nil),        // 3: proto.DictionaryLookupResponses
	(*DictionaryLookupResponse)(nil),         // 4: proto.DictionaryLookupResponse
}
var file_proto_translator_user_proto_depIdxs = []int32{
	2, // 0: proto.DictionaryLookupResponses.Results:type_name -> proto.DictionaryResponse
	2, // 1: proto.DictionaryLookupResponse.Result:type_name -> proto.DictionaryResponse
	0, // 2: proto.TranslatorUser.DictionaryLookup:input_type -> proto.DictionaryLookupParameter
	1, // 3: proto.TranslatorUser.DictionaryLookupWithPos:input_type -> proto.DictionaryLookupWithPosParameter
	3, // 4: proto.TranslatorUser.DictionaryLookup:output_type -> proto.DictionaryLookupResponses
	4, // 5: proto.TranslatorUser.DictionaryLookupWithPos:output_type -> proto.DictionaryLookupResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_translator_user_proto_init() }
func file_proto_translator_user_proto_init() {
	if File_proto_translator_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_translator_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryLookupParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryLookupWithPosParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryLookupResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryLookupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_translator_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translator_user_proto_goTypes,
		DependencyIndexes: file_proto_translator_user_proto_depIdxs,
		MessageInfos:      file_proto_translator_user_proto_msgTypes,
	}.Build()
	File_proto_translator_user_proto = out.File
	file_proto_translator_user_proto_rawDesc = nil
	file_proto_translator_user_proto_goTypes = nil
	file_proto_translator_user_proto_depIdxs = nil
}
