// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: proto/translator_admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslationFindParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2  string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Letter string `protobuf:"bytes,2,opt,name=letter,proto3" json:"letter,omitempty"`
}

func (x *TranslationFindParameter) Reset() {
	*x = TranslationFindParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationFindParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationFindParameter) ProtoMessage() {}

func (x *TranslationFindParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationFindParameter.ProtoReflect.Descriptor instead.
func (*TranslationFindParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TranslationFindParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationFindParameter) GetLetter() string {
	if x != nil {
		return x.Letter
	}
	return ""
}

type TranslationFindByTextAndPosParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2 string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos   int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *TranslationFindByTextAndPosParameter) Reset() {
	*x = TranslationFindByTextAndPosParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationFindByTextAndPosParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationFindByTextAndPosParameter) ProtoMessage() {}

func (x *TranslationFindByTextAndPosParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationFindByTextAndPosParameter.ProtoReflect.Descriptor instead.
func (*TranslationFindByTextAndPosParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TranslationFindByTextAndPosParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationFindByTextAndPosParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationFindByTextAndPosParameter) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type TranslationFindByTextParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2 string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TranslationFindByTextParameter) Reset() {
	*x = TranslationFindByTextParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationFindByTextParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationFindByTextParameter) ProtoMessage() {}

func (x *TranslationFindByTextParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationFindByTextParameter.ProtoReflect.Descriptor instead.
func (*TranslationFindByTextParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{2}
}

func (x *TranslationFindByTextParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationFindByTextParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranslationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2      string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos        int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Translated string `protobuf:"bytes,4,opt,name=translated,proto3" json:"translated,omitempty"`
	Provider   string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *TranslationResponse) Reset() {
	*x = TranslationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationResponse) ProtoMessage() {}

func (x *TranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationResponse.ProtoReflect.Descriptor instead.
func (*TranslationResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{3}
}

func (x *TranslationResponse) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationResponse) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *TranslationResponse) GetTranslated() string {
	if x != nil {
		return x.Translated
	}
	return ""
}

func (x *TranslationResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type TranslationFindResposne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*TranslationResponse `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *TranslationFindResposne) Reset() {
	*x = TranslationFindResposne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationFindResposne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationFindResposne) ProtoMessage() {}

func (x *TranslationFindResposne) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationFindResposne.ProtoReflect.Descriptor instead.
func (*TranslationFindResposne) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{4}
}

func (x *TranslationFindResposne) GetResults() []*TranslationResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type TranslationAddParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2      string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos        int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Translated string `protobuf:"bytes,4,opt,name=translated,proto3" json:"translated,omitempty"`
}

func (x *TranslationAddParameter) Reset() {
	*x = TranslationAddParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationAddParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationAddParameter) ProtoMessage() {}

func (x *TranslationAddParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationAddParameter.ProtoReflect.Descriptor instead.
func (*TranslationAddParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{5}
}

func (x *TranslationAddParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationAddParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationAddParameter) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *TranslationAddParameter) GetTranslated() string {
	if x != nil {
		return x.Translated
	}
	return ""
}

type TranslationAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TranslationAddResponse) Reset() {
	*x = TranslationAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationAddResponse) ProtoMessage() {}

func (x *TranslationAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationAddResponse.ProtoReflect.Descriptor instead.
func (*TranslationAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{6}
}

type TranslationUpdateParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2      string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos        int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Translated string `protobuf:"bytes,4,opt,name=translated,proto3" json:"translated,omitempty"`
}

func (x *TranslationUpdateParameter) Reset() {
	*x = TranslationUpdateParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationUpdateParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationUpdateParameter) ProtoMessage() {}

func (x *TranslationUpdateParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationUpdateParameter.ProtoReflect.Descriptor instead.
func (*TranslationUpdateParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{7}
}

func (x *TranslationUpdateParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationUpdateParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationUpdateParameter) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *TranslationUpdateParameter) GetTranslated() string {
	if x != nil {
		return x.Translated
	}
	return ""
}

type TranslationUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TranslationUpdateResponse) Reset() {
	*x = TranslationUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationUpdateResponse) ProtoMessage() {}

func (x *TranslationUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationUpdateResponse.ProtoReflect.Descriptor instead.
func (*TranslationUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{8}
}

type TranslationRemoveParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang2 string `protobuf:"bytes,1,opt,name=lang2,proto3" json:"lang2,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Pos   int32  `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *TranslationRemoveParameter) Reset() {
	*x = TranslationRemoveParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationRemoveParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationRemoveParameter) ProtoMessage() {}

func (x *TranslationRemoveParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationRemoveParameter.ProtoReflect.Descriptor instead.
func (*TranslationRemoveParameter) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{9}
}

func (x *TranslationRemoveParameter) GetLang2() string {
	if x != nil {
		return x.Lang2
	}
	return ""
}

func (x *TranslationRemoveParameter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationRemoveParameter) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

type TranslationRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TranslationRemoveResponse) Reset() {
	*x = TranslationRemoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_translator_admin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslationRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationRemoveResponse) ProtoMessage() {}

func (x *TranslationRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translator_admin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationRemoveResponse.ProtoReflect.Descriptor instead.
func (*TranslationRemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_translator_admin_proto_rawDescGZIP(), []int{10}
}

var File_proto_translator_admin_proto protoreflect.FileDescriptor

var file_proto_translator_admin_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x22,
	0x62, 0x0a, 0x24, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x79, 0x54, 0x65, 0x78, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x22, 0x4a, 0x0a, 0x1e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x8d, 0x01, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22,
	0x4f, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x6e, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x22, 0x75, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x64, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x6e, 0x67, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67,
	0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x78, 0x0a, 0x1a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x1a, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x32, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70,
	0x6f, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xca, 0x04, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x62, 0x0a, 0x1d, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4c, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x73, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x54, 0x65, 0x78, 0x74,
	0x41, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x12, 0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79,
	0x54, 0x65, 0x78, 0x74, 0x41, 0x6e, 0x64, 0x50, 0x6f, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x61, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73,
	0x6e, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5a, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x6d, 0x0a, 0x20,
	0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x42, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x6a, 0x69, 0x6c, 0x61, 0x62, 0x6f, 0x2f, 0x63, 0x6f,
	0x63, 0x6f, 0x74, 0x6f, 0x6c, 0x61, 0x2d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_translator_admin_proto_rawDescOnce sync.Once
	file_proto_translator_admin_proto_rawDescData = file_proto_translator_admin_proto_rawDesc
)

func file_proto_translator_admin_proto_rawDescGZIP() []byte {
	file_proto_translator_admin_proto_rawDescOnce.Do(func() {
		file_proto_translator_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_translator_admin_proto_rawDescData)
	})
	return file_proto_translator_admin_proto_rawDescData
}

var file_proto_translator_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_translator_admin_proto_goTypes = []interface{}{
	(*TranslationFindParameter)(nil),             // 0: proto.TranslationFindParameter
	(*TranslationFindByTextAndPosParameter)(nil), // 1: proto.TranslationFindByTextAndPosParameter
	(*TranslationFindByTextParameter)(nil),       // 2: proto.TranslationFindByTextParameter
	(*TranslationResponse)(nil),                  // 3: proto.TranslationResponse
	(*TranslationFindResposne)(nil),              // 4: proto.TranslationFindResposne
	(*TranslationAddParameter)(nil),              // 5: proto.TranslationAddParameter
	(*TranslationAddResponse)(nil),               // 6: proto.TranslationAddResponse
	(*TranslationUpdateParameter)(nil),           // 7: proto.TranslationUpdateParameter
	(*TranslationUpdateResponse)(nil),            // 8: proto.TranslationUpdateResponse
	(*TranslationRemoveParameter)(nil),           // 9: proto.TranslationRemoveParameter
	(*TranslationRemoveResponse)(nil),            // 10: proto.TranslationRemoveResponse
}
var file_proto_translator_admin_proto_depIdxs = []int32{
	3,  // 0: proto.TranslationFindResposne.Results:type_name -> proto.TranslationResponse
	0,  // 1: proto.TranslatorAdmin.FindTranslationsByFirstLetter:input_type -> proto.TranslationFindParameter
	1,  // 2: proto.TranslatorAdmin.FindTranslationByTextAndPos:input_type -> proto.TranslationFindByTextAndPosParameter
	2,  // 3: proto.TranslatorAdmin.FindTranslationsByText:input_type -> proto.TranslationFindByTextParameter
	5,  // 4: proto.TranslatorAdmin.AddTranslation:input_type -> proto.TranslationAddParameter
	7,  // 5: proto.TranslatorAdmin.UpdateTranslation:input_type -> proto.TranslationUpdateParameter
	9,  // 6: proto.TranslatorAdmin.RemoveTranslation:input_type -> proto.TranslationRemoveParameter
	4,  // 7: proto.TranslatorAdmin.FindTranslationsByFirstLetter:output_type -> proto.TranslationFindResposne
	3,  // 8: proto.TranslatorAdmin.FindTranslationByTextAndPos:output_type -> proto.TranslationResponse
	4,  // 9: proto.TranslatorAdmin.FindTranslationsByText:output_type -> proto.TranslationFindResposne
	6,  // 10: proto.TranslatorAdmin.AddTranslation:output_type -> proto.TranslationAddResponse
	6,  // 11: proto.TranslatorAdmin.UpdateTranslation:output_type -> proto.TranslationAddResponse
	10, // 12: proto.TranslatorAdmin.RemoveTranslation:output_type -> proto.TranslationRemoveResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_translator_admin_proto_init() }
func file_proto_translator_admin_proto_init() {
	if File_proto_translator_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_translator_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationFindParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationFindByTextAndPosParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationFindByTextParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationFindResposne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationAddParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationUpdateParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationRemoveParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_translator_admin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslationRemoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_translator_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translator_admin_proto_goTypes,
		DependencyIndexes: file_proto_translator_admin_proto_depIdxs,
		MessageInfos:      file_proto_translator_admin_proto_msgTypes,
	}.Build()
	File_proto_translator_admin_proto = out.File
	file_proto_translator_admin_proto_rawDesc = nil
	file_proto_translator_admin_proto_goTypes = nil
	file_proto_translator_admin_proto_depIdxs = nil
}
