---
on: [pull_request]
name: Reviewdog
jobs:
  # staticcheck:
  #   name: runner / staticcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: "1.17"
  #     - uses: reviewdog/action-staticcheck@v1
  #       with:
  #         github_token: ${{ secrets.REVIEWDOG_TOKEN }}
  #         reporter: github-pr-review
  #         filter_mode: nofilter
  #         fail_on_error: true
  staticcheck:
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: staticcheck
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--config=.github/.golangci.yml --disable-all -E staticcheck --timeout=10m"
          tool_name: staticcheck
          filter_mode: nofilter
          fail_on_error: true

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          # golangci_lint_flags: "--enable-all --exclude-use-default=false"
          fail_on_error: true

  errcheck:
    name: runner / errcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: errcheck
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E errcheck --timeout=10m"
          tool_name: errcheck
          filter_mode: nofilter
          fail_on_error: true

  gosec:
    name: runner / gosec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gosec
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E gosec --timeout=10m"
          tool_name: gosec
          fail_on_error: true

  # dupl:
  #   name: runner / dupl
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: dupl
  #       uses: reviewdog/action-golangci-lint@v2
  #       with:
  #         github_token: ${{ secrets.REVIEWDOG_TOKEN }}
  #         reporter: github-pr-review
  #         golangci_lint_flags: "--disable-all -E dupl --timeout=10m"
  #         tool_name: dupl
  #         filter_mode: nofilter
  #         fail_on_error: true

  gofmt:
    name: runner / gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gofmt
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E gofmt --timeout=10m"
          tool_name: gofmt
          filter_mode: nofilter
          fail_on_error: true

  unconvert:
    name: runner / unconvert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unconvert
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E unconvert --timeout=10m"
          tool_name: unconvert
          filter_mode: nofilter
          fail_on_error: true

  gomnd:
    name: runner / gomnd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gomnd
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E gomnd --timeout=10m"
          tool_name: gomnd
          filter_mode: nofilter
          fail_on_error: true

  errorlint:
    name: runner / errorlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: errorlint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E errorlint --timeout=10m"
          tool_name: errorlint
          filter_mode: nofilter
          fail_on_error: true


  gocyclo:
    name: runner / gocyclo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gocyclo
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--config=.github/.golangci.yml --disable-all --tests=false -E gocyclo --timeout=10m"
          tool_name: gocyclo
          filter_mode: nofilter
          fail_on_error: true

  goimports:
    name: runner / goimports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: goimports
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          golangci_lint_flags: "--disable-all -E goimports --timeout=10m"
          tool_name: goimports
          fail_on_error: true

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          locale: "US"
          fail_on_error: true

  yamllint:
    name: runner / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: github-pr-review
          yamllint_flags: "-c .github/.yamllint.yml ."
          fail_on_error: true
